CREATE TABLE IF NOT EXISTS public.tasks (
  id bigint generated by default as identity primary key,
  category text,
  activity text,
  responsible text,
  status text,
  priority text default 'Média',
  created_at date default CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS public.projects (
  id bigint generated by default as identity primary key,
  name text,
  category text,
  owner text,
  deadline date,
  executive_status text,
  objective text,
  scope text,
  summary text,
  created_at timestamp with time zone default now(),
  updated_at timestamp with time zone default now()
);

CREATE TABLE IF NOT EXISTS public.evidences (
  id bigint generated by default as identity primary key,
  task_id bigint references public.tasks(id) ON DELETE CASCADE,
  file_name text,
  file_type text,
  note text,
  storage_path text,
  created_at timestamp with time zone default now()
);
