// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Banco descartável usado APENAS por `prisma migrate dev` para validar migrations.
    // Aponta para o Postgres local (docker-compose.dev.yml). O Supabase nunca é usado como shadow.
    shadowDatabaseUrl: process.env["SHADOW_DATABASE_URL"],
  },
});
