-- Existing users were created before action permissions existed.
-- Backfill only untouched permission objects so explicit individual choices are preserved.
UPDATE "users"
SET "permissions" = CASE "role"
  WHEN 'Estagiario' THEN '{"users.view":true,"diretorias.view":true,"tasks.view":true,"tasks.edit":true,"events.view":true,"absences.view":true,"absences.create":true}'::jsonb
  WHEN 'Funcionario' THEN '{"users.view":true,"diretorias.view":true,"projects.view":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"events.view":true,"events.create":true,"absences.view":true,"absences.create":true}'::jsonb
  WHEN 'Tecnico' THEN '{"users.view":true,"diretorias.view":true,"projects.view":true,"projects.edit":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"tasks.archive":true,"events.view":true,"events.create":true,"absences.view":true,"absences.create":true}'::jsonb
  WHEN 'Coordenador' THEN '{"users.view":true,"diretorias.view":true,"projects.view":true,"projects.create":true,"projects.edit":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"tasks.archive":true,"events.view":true,"events.create":true,"events.edit":true,"absences.view":true,"absences.create":true,"dashboards.view":true}'::jsonb
  WHEN 'Gerente' THEN '{"users.view":true,"users.create":true,"users.edit_profile":true,"users.delete":true,"users.reset_password":true,"users.manage_access":true,"projects.view":true,"projects.create":true,"projects.edit":true,"projects.delete":true,"projects.import":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"tasks.delete":true,"tasks.archive":true,"tasks.import":true,"events.view":true,"events.create":true,"events.edit":true,"events.delete":true,"absences.view":true,"absences.create":true,"absences.edit":true,"absences.delete":true,"absences.approve":true,"absences.view_all":true,"diretorias.view":true,"dashboards.view":true,"logs.view":true,"settings.manage_directoria":true,"feedback.manage":true}'::jsonb
  WHEN 'Diretor' THEN '{"users.view":true,"users.create":true,"users.edit_profile":true,"users.delete":true,"users.reset_password":true,"users.manage_access":true,"projects.view":true,"projects.create":true,"projects.edit":true,"projects.delete":true,"projects.import":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"tasks.delete":true,"tasks.archive":true,"tasks.import":true,"events.view":true,"events.create":true,"events.edit":true,"events.delete":true,"absences.view":true,"absences.create":true,"absences.edit":true,"absences.delete":true,"absences.approve":true,"absences.view_all":true,"diretorias.view":true,"dashboards.view":true,"logs.view":true,"settings.manage_directoria":true,"feedback.manage":true}'::jsonb
  WHEN 'Admin' THEN '{"users.view":true,"users.create":true,"users.edit_profile":true,"users.delete":true,"users.reset_password":true,"users.manage_access":true,"projects.view":true,"projects.create":true,"projects.edit":true,"projects.delete":true,"projects.import":true,"tasks.view":true,"tasks.create":true,"tasks.edit":true,"tasks.delete":true,"tasks.archive":true,"tasks.import":true,"events.view":true,"events.create":true,"events.edit":true,"events.delete":true,"absences.view":true,"absences.create":true,"absences.edit":true,"absences.delete":true,"absences.approve":true,"absences.view_all":true,"diretorias.view":true,"diretorias.manage":true,"dashboards.view":true,"logs.view":true,"logs.clear":true,"settings.manage_directoria":true,"settings.manage_permission_presets":true,"feedback.manage":true}'::jsonb
  ELSE '{}'::jsonb
END
WHERE "permissions" = '{}'::jsonb;